# Generated by Django 4.2.5 on 2023-09-16 20:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=20, null=True)),
                ('precio', models.IntegerField(default=1000)),
                ('tasaciones_maximas', models.IntegerField(default=50)),
                ('guardados_maximos', models.IntegerField(default=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('habitaciones', models.IntegerField(default=0)),
                ('baños', models.IntegerField(default=0)),
                ('toilets', models.IntegerField(default=0)),
                ('dormitorios', models.IntegerField(default=0)),
                ('pisos', models.IntegerField(default=0)),
                ('pileta', models.BooleanField(default=False)),
                ('parrilla', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('apodo', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('tasaciones_realizadas', models.IntegerField(default=0)),
                ('guardados_realizadas', models.IntegerField(default=0)),
                ('id_plan', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Tasacion',
            fields=[
                ('id_tasacion', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fecha_tasacion', models.TimeField(default=datetime.datetime(2023, 9, 16, 17, 44, 12, 990059))),
                ('precio', models.IntegerField(null=True)),
                ('moneda', models.CharField(max_length=3, null=True)),
                ('id_Propiedad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.propiedad')),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='id_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
