# Generated by Django 4.2.5 on 2023-09-21 23:24

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('apodo', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('tasaciones_realizadas', models.IntegerField(default=0)),
                ('guardados_realizadas', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=20, null=True)),
                ('precio', models.IntegerField(default=1000)),
                ('tasaciones_maximas', models.IntegerField(default=50)),
                ('guardados_maximos', models.IntegerField(default=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('habitaciones', models.IntegerField(default=0)),
                ('baños', models.IntegerField(default=0)),
                ('toilets', models.IntegerField(default=0)),
                ('dormitorios', models.IntegerField(default=0)),
                ('pisos', models.IntegerField(default=0)),
                ('pileta', models.BooleanField(default=False)),
                ('parrilla', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_usuario', 'calle', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Tasacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tasacion', models.DateTimeField(default=datetime.datetime(2023, 9, 21, 20, 24, 48, 45330))),
                ('precio', models.IntegerField(null=True)),
                ('id_Propiedad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.propiedad')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.plan'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
