# Generated by Django 5.0a1 on 2023-10-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='precio',
        ),
    ]
