# Generated by Django 5.0a1 on 2023-10-13 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='habitaciones',
            new_name='ambientes',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='toilets',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='AC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='balcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cochera',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=99)]),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='googleMaps',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='lavadero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=99999)]),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precioxLocalidad',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=9999)]),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='toilette',
            field=models.BooleanField(default=False),
        ),
    ]
