# Generated by Django 5.0a1 on 2023-09-24 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacion',
            name='fecha_tasacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 14, 3, 33, 634456)),
        ),
    ]
