# Generated by Django 5.0a1 on 2023-10-04 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacion',
            name='fecha_tasacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 21, 15, 37, 374596)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
