# Generated by Django 4.2.5 on 2023-09-16 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacion',
            name='fecha_tasacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 19, 16, 23, 329662)),
        ),
    ]
