# Generated by Django 5.0a1 on 2023-09-24 17:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tasacion_fecha_tasacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='guardados_maximos',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=9999)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=9999999)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tasaciones_maximas',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=9999)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='baños',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=20)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='dormitorios',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=20)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='habitaciones',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=20)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='numero',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=9999)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='pisos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=20)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='toilets',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=20)]),
        ),
        migrations.AlterField(
            model_name='tasacion',
            name='fecha_tasacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 14, 39, 7, 895721)),
        ),
        migrations.AlterField(
            model_name='tasacion',
            name='precio',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=9999999)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='guardados_realizadas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=9999)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tasaciones_realizadas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=9999)]),
        ),
    ]
