# Generated by Django 5.0a1 on 2023-10-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_habitaciones_propiedad_ambientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='googleMaps',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
