# Generated by Django 5.0a1 on 2023-09-24 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plan_guardados_maximos_alter_plan_precio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasacion',
            old_name='id_Propiedad',
            new_name='id_propiedad',
        ),
        migrations.AlterField(
            model_name='tasacion',
            name='fecha_tasacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 14, 54, 16, 428875)),
        ),
    ]
