# Generated by Django 5.0a1 on 2023-10-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_propiedad_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='pisos',
        ),
    ]
