# Generated by Django 5.0a1 on 2023-09-24 18:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_id_propiedad_tasacion_id_propiedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacion',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasacion',
            name='fecha_tasacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 15, 13, 47, 645540)),
        ),
    ]
