insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (1, '9 de Abril', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (2, 'Abasto', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (3, 'Adolfo Gonz les Chaves', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (4, 'Aeropuerto Internacional Ezeiza', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (5, 'agronomía', 1597);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (6, 'Alejandro Peti n', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (7, 'almagro', 1685);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (8, 'Argentina', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (9, 'Avellaneda', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (10, 'balvanera', 1421);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (11, 'barracas', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (12, 'Barrio Los Pinos', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (13, 'Barrio Los Pioneros', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (14, 'Barrio Mendizabal', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (15, 'Barrio Parque El Remanso', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (16, 'Barrio Parque Exaltaci n de la Cruz', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (17, 'Barrio Parque Jular', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (18, 'Barrio Parque Las Acacias', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (19, 'Bel n de Escobar', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (20, 'belgrano', 2138);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (21, 'Benav dez', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (22, 'Berazategui', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (23, 'Berisso', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (24, 'boedo', 1570);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (25, 'Brandsen', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (26, 'Buenos Aires', 1048);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (27, 'C rdoba', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (28, 'Ca uelas', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (29, 'caballito', 1861);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (30, 'Campana', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (31, 'Canning', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (32, 'Capilla del Se or', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (33, 'Carlos Spegazzini', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (34, 'chacarita', 1658);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (35, 'City Bell', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (36, 'Ciudad del Plata', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (37, 'coghlan', 1803);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (38, 'colegiales', 1912);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (39, 'Comodoro Py', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (40, 'constitución', 1161);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (41, 'Del Viso', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (42, 'Dique Luj n', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (43, 'Dock Sud', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (44, 'Domselaar', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (45, 'Donostia - San Sebasti n', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (46, 'El Cazador', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (47, 'El Jag el', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (48, 'El Pato', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (49, 'El Peligro', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (50, 'El Tri ngulo', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (51, 'Ensenada', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (52, 'Ezeiza', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (53, 'Ezpeleta', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (54, 'flores', 1542);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (55, 'floresta', 1449);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (56, 'Francisco  lvarez', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (57, 'Gar n', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (58, 'General Las Heras', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (59, 'Gerli', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (60, 'Grand Bourg', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (61, 'Greenville', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (62, 'Gualeguaych', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (63, 'Hudson', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (64, 'Ingeniero Maschwitz', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (65, 'Jeppener', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (66, 'Jos  Hern ndez', 1622);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (67, 'Juan Mar a Guti rrez', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (68, 'la boca', 1150);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (69, 'La Plata', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (70, 'La Tablada', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (71, 'La Uni n', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (72, 'Lan s Este', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (73, 'Lan s Oeste', 1622);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (74, 'liniers', 1502);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (75, 'Llavallol', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (76, 'Loma Verde', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (77, 'Lomas de Copello', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (78, 'Lomas del R o Luj n', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (79, 'Los Cardales', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (80, 'Los Hornos', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (81, 'Los Talas', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (82, 'Luis Guill n', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (83, 'Luxembourg', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (84, 'M ximo Paz', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (85, 'Malibu', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (86, 'Manuel Alberti', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (87, 'Manzanares', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (88, 'Maquinista Savio', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (89, 'Mar del Plata', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (90, 'mataderos', 1416);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (91, 'Matheu', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (92, 'monserrat', 1448);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (93, 'monte castro', 1574);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (94, 'Monte Chingolo', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (95, 'Monte Grande', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (96, 'Mor n', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (97, 'Municipio de Jacinto Ar uz', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (98, 'Necochea', 1622);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (99, 'ngel Etcheverry', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (100, 'Nordelta', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (101, 'nueva pompeya', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (102, 'nuñez', 2002);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (103, 'Oliden', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (104, 'palermo', 2079);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (105, 'Parada Robles', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (106, 'Paraje El Taladro', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (107, 'parque avellaneda', 1262);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (108, 'parque chacabuco', 1560);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (109, 'parque chas', 1640);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (110, 'parque patricios', 1337);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (111, 'Partido de Almirante Brown', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (112, 'Partido de Lan s', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (113, 'paternal', 1456);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (114, 'Pav n', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (115, 'Pereyra', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (116, 'Pi eyro', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (117, 'Pilar', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (118, 'Pilar Sur', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (119, 'Pl tanos', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (120, 'Primera Secci n', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (121, 'puerto madero', 3993);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (122, 'Punta Alta', 1622);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (123, 'Punta Lara', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (124, 'Quilmes', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (125, 'Ranelagh', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (126, 'recoleta', 1978);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (127, 'retiro', 1682);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (128, 'Rinc n de Milberg', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (129, 'Rosario', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (130, 'saavedra', 1916);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (131, 'Samboromb n', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (132, 'san cristobal', 1443);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (133, 'San Isidro', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (134, 'San Juan', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (135, 'san nicolas', 1431);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (136, 'San Sebasti n', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (137, 'san telmo', 1537);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (138, 'San Vicente', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (139, 'Sarand', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (140, 'Sourigues', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (141, 'Temperley', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (142, 'Tigre', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (143, 'Tolosa', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (144, 'Torres', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (145, 'Trist n Su rez', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (146, 'Troncos del Talar', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (147, 'Turdera', 1622);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (148, 'Valent n Alsina', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (149, 'Venado Tuerto', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (150, 'versalles', 1472);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (151, 'villa crespo', 1709);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (152, 'villa del parque', 1685);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (153, 'villa devoto', 1756);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (154, 'Villa Dom nico', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (155, 'Villa Elvira', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (156, 'Villa Espa a', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (157, 'villa general mitre', 1501);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (158, 'villa lugano', 1048);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (159, 'villa luro', 1501);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (160, 'villa ortuzar', 1617);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (161, 'villa pueyrredon', 1677);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (162, 'villa real', 1575);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (163, 'Villa Rosa', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (164, 'villa santa rita', 1485);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (165, 'villa soldati', 899);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (166, 'villa urquiza', 1939);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (167, 'Villa Zula', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (168, 'Virrey Del Pino', 1478);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (169, 'Wilde', 1097);
insert into main.api_precioxlocalidad (id, ciudad, precioxLocalidad) values (170, 'Zelaya', 1097);
